# [language-server.rust-analyzer.config]
# # checkOnSave.allTargets = false
# # checkOnSave.extraArgs = [ "--target", "thumbv7m-none-eabi" ]
# # procMacro.enable = true
# checkOnSave = { command = "clippy" }
# cargo = { allFeatures = true, allTargets = true}
[language-server.rust-analyzer.config]                                                                                                               
diagnostics.disabled = ["inactive-code"]
